server:
  port: 6603
spring:
  application:
    name: sign
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active}
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: ${data.sentinel.dashboard.url}

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:nacos:sign.yml


---
spring:
  config:
    activate:
      on-profile: product
    import:
      optional:nacos:sign.yml


